import './styles.css';

const KEY='wydoc_crm_v12';
const baseDefaults={
  name:'WyDoc CRM',currency:'USD',timezone:'Africa/Lagos',theme:'Light',session:true,
  customers:[
    {id:1,name:'Acme Industries',email:'hello@acme.example',phone:'+1 555 0101',company:'Acme Industries',status:'Active',type:'Enterprise',source:'Website',tags:['VIP'],notes:'Key renewal account.'},
    {id:2,name:'Northstar Studio',email:'team@northstar.example',phone:'+1 555 0102',company:'Northstar Studio',status:'Active',type:'Agency',source:'Referral',tags:['Returning'],notes:''},
    {id:3,name:'Greenline Services',email:'contact@greenline.example',phone:'+1 555 0103',company:'Greenline Services',status:'At Risk',type:'Services',source:'Website',tags:['Follow-up'],notes:'Needs account review.'},
    {id:4,name:'Bright Academy',email:'admin@bright.example',phone:'+1 555 0104',company:'Bright Academy',status:'Active',type:'Education',source:'Partner',tags:[],notes:''}
  ],
  leads:[
    {id:5,name:'Liam Carter',email:'liam@example.com',source:'Website',stage:'Qualified',value:8500,priority:'High'},
    {id:6,name:'Amina Yusuf',email:'amina@example.com',source:'Referral',stage:'New',value:4200,priority:'Medium'},
    {id:7,name:'Daniel Reed',email:'daniel@example.com',source:'LinkedIn',stage:'Proposal',value:12000,priority:'High'},
    {id:8,name:'Maya Stone',email:'maya@example.com',source:'Partner',stage:'Negotiation',value:18000,priority:'High'}
  ],
  deals:[
    {id:9,name:'Acme Renewal',customer:'Acme Industries',stage:'Negotiation',value:18000,probability:72},
    {id:10,name:'Northstar Website',customer:'Northstar Studio',stage:'Proposal',value:12000,probability:55},
    {id:11,name:'Greenline Retainer',customer:'Greenline Services',stage:'Qualified',value:8500,probability:35}
  ],
  tasks:[
    {id:12,title:'Follow up with Acme',due:'Today',priority:'High',status:'Open'},
    {id:13,title:'Send proposal to Daniel',due:'Tomorrow',priority:'Medium',status:'Open'},
    {id:14,title:'Review Greenline account',due:'Sep 15',priority:'High',status:'Open'}
  ],
  activities:[],appointments:[],documents:[],tags:['VIP','Returning','Follow-up'],
  team:[{id:15,name:'Admin User',email:'admin@example.com',role:'Owner',status:'Active'},{id:16,name:'Sales Manager',email:'sales@example.com',role:'Manager',status:'Active'}],
  audit:[],notifications:[]
};
const clone=o=>JSON.parse(JSON.stringify(o));
let state=load(); let page='Dashboard'; let search='';
const recordKeys=['customers','leads','deals','tasks','activities','appointments','documents','team','audit','notifications'];
let idCounter=recordKeys.reduce((max,k)=>Math.max(max,...state[k].map(x=>Number(x.id)||0)),Date.now());

function esc(v){return String(v??'').replace(/[&<>'"|]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;','|':'&#124;'}[c]))}
function load(){try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');return saved?normalize({...clone(baseDefaults),...saved}):clone(baseDefaults)}catch{return clone(baseDefaults)}}
function normalize(s){
  for(const k of recordKeys){
    if(!Array.isArray(s[k]))s[k]=clone(baseDefaults[k]);
    else s[k]=s[k].filter(x=>typeof x==='object'&&x!==null);
  }
  s.tags=Array.isArray(s.tags)?s.tags.filter(t=>typeof t==='string'&&t.trim()).map(t=>t.trim()).filter((t,i,a)=>a.findIndex(x=>x.toLowerCase()===t.toLowerCase())===i):clone(baseDefaults.tags);
  s.name=typeof s.name==='string'&&s.name.trim()?s.name.trim():'WyDoc CRM';
  s.timezone=typeof s.timezone==='string'&&s.timezone.trim()?s.timezone.trim():'UTC';
  s.theme=s.theme==='Dark'?'Dark':'Light';
  s.currency=typeof s.currency==='string'&&/^[A-Za-z]{3}$/.test(s.currency.trim())?s.currency.trim().toUpperCase():'USD';
  s.session=s.session!==false;
  return s;
}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch(e){console.error('CRM storage error',e);toast?.('Unable to save local data. Browser storage may be full or blocked.','error');return false}}
function nextId(){return ++idCounter}
function money(v){try{return new Intl.NumberFormat(undefined,{style:'currency',currency:state.currency||'USD',maximumFractionDigits:0}).format(Number(v)||0)}catch{return `${state.currency||'USD'} ${Number(v)||0}`}}
function audit(action,entity='System'){state.audit.unshift({id:nextId(),action,entity,date:new Date().toLocaleString()});state.audit=state.audit.slice(0,200);save()}
function toast(msg,type='success'){document.querySelector('#toast')?.remove();document.body.insertAdjacentHTML('beforeend',`<div id="toast" class="toast ${type}">${esc(msg)}</div>`);setTimeout(()=>document.querySelector('#toast')?.remove(),2600)}
function add(arr,item,label){document.querySelector('#modal')?.remove();item.id=nextId();state[arr].unshift(item);audit(`Created ${label||arr.slice(0,-1)}`,item.name||item.title||item.customer||'Item');save();toast(`${label||'Item'} created`);render()}
function del(arr,id,label){if(!confirm('Delete this item? This cannot be undone.'))return;const before=state[arr].length;state[arr]=state[arr].filter(x=>x.id!==id);if(state[arr].length===before)return toast('Item not found','error');audit(`Deleted ${label||arr.slice(0,-1)}`);save();toast('Deleted');render()}
function update(arr,id,patch,label){const x=state[arr].find(x=>x.id===id);if(!x)return toast('Record not found','error');Object.assign(x,patch);audit(`Updated ${label||arr.slice(0,-1)}`,x.name||x.title||x.customer||'Item');save();toast('Saved');render()}
function nav(){return [['Dashboard','⌂'],['Customers','♙'],['Leads','＋'],['Deals','▦'],['Tasks','✓'],['Appointments','◷'],['Activities','↻'],['Reports','▥'],['Documents','□'],['Tags','#'],['Team & Roles','♙'],['Audit Log','≡'],['Settings','⚙']]}
function layout(){if(!state.session){document.querySelector('#app').innerHTML=`<div class="login"><div class="loginBox"><div class="brand"><span>W</span><b>${esc(state.name)}</b></div><h1>Workspace signed out</h1><p>This demo session is closed. Re-enter the demo workspace to continue.</p>${btn('Enter workspace','signin','primary')}</div></div>`;bindView();return}document.querySelector('#app').innerHTML=`<div class="app"><aside id="side" class="side"><div class="brand"><span>W</span><b>${esc(state.name)}</b></div><nav>${nav().map(([n,icon])=>`<button class="nav ${page===n?'active':''}" data-page="${n}"><i>${icon}</i><span>${n}</span></button>`).join('')}</nav><button class="nav" data-action="signout"><i>↪</i><span>Sign out</span></button></aside><main><header><button class="icon" data-action="collapse">☰</button><label class="search">⌕<input id="search" value="${esc(search)}" placeholder="Search customers, leads, deals…"></label><button class="icon notificationBtn" data-action="notify" title="Notifications">♢${state.notifications.length?`<sup>${Math.min(9,state.notifications.length)}</sup>`:''}</button><span class="avatar">AD</span></header><section class="content"><div class="crumb">Workspace / <b>${esc(page)}</b></div><div id="view"></div></section></main></div><div id="toastHost"></div>`;document.querySelector('#search').addEventListener('input',e=>{search=e.target.value;renderView()});renderView()}
function render(){document.body.classList.toggle('dark',state.theme==='Dark');document.documentElement.style.colorScheme=state.theme==='Dark'?'dark':'light';layout()}
function renderView(){const v=document.querySelector('#view');if(!v)return;try{const view=views[page]||dashboard;v.innerHTML=view();bindView()}catch(e){console.error(e);v.innerHTML=empty('This section could not be rendered. Please reload or restore a valid backup.');toast('Unable to render this section','error')}}
function filtered(arr,fields){const q=search.toLowerCase().trim();return q?arr.filter(x=>fields.some(f=>String(x[f]??'').toLowerCase().includes(q))):arr}
function btn(text,action,cls='secondary'){return `<button class="${cls}" data-action="${esc(action)}">${text}</button>`}
const views={Dashboard:dashboard,Customers:customers,Leads:leads,Deals:deals,Tasks:tasks,Appointments:appointments,Activities:activities,Reports:reports,Documents:documents,Tags:tags,'Team & Roles':team,'Audit Log':auditPage,Settings:settings};
function dashboard(){const pipeline=state.deals.reduce((a,d)=>a+Number(d.value||0),0),openTasks=state.tasks.filter(t=>t.status!=='Done').length;return `<div class="titleRow"><div><h1>Good morning 👋</h1><p>Here is what's happening with your customers today.</p></div>${btn('＋ Add customer','add-customer','primary')}</div><div class="cards">${card('Customers',state.customers.length,'Live')} ${card('Active leads',state.leads.filter(l=>!['Won','Lost'].includes(l.stage)).length,'Live')} ${card('Open deals',state.deals.filter(d=>!['Won','Lost'].includes(d.stage)).length,'Live')} ${card('Pipeline',money(pipeline),'Live')}</div><div class="grid2"><section class="panel"><div class="panelHead"><h3>Sales pipeline</h3>${btn('View all','goto-deals')}</div>${['New','Qualified','Proposal','Negotiation','Won'].map(s=>{const n=state.deals.filter(d=>d.stage===s).length;const pct=state.deals.length?Math.round(n/state.deals.length*100):0;return `<div class="bar"><div><span>${s}</span><b>${n}</b></div><i><em style="width:${pct}%"></em></i></div>`}).join('')}</section><section class="panel"><div class="panelHead"><h3>Upcoming tasks</h3>${btn('View all','goto-tasks')}</div>${state.tasks.filter(t=>t.status!=='Done').slice(0,4).map(t=>`<div class="task"><span class="dot"></span><div><b>${esc(t.title)}</b><small>${esc(t.due)} · ${esc(t.priority)} priority</small></div></div>`).join('')||empty('No open tasks')}</section></div><section class="panel"><div class="panelHead"><h3>Recent customers</h3>${btn('Manage','goto-customers')}</div>${customerTable(state.customers.slice(0,5))}</section>`}
function card(a,b,c){return `<div class="card"><span>${a}</span><strong>${b}</strong><small>${c}</small></div>`}
function customerTable(rows){return `<div class="tableWrap"><table><thead><tr><th>Customer</th><th>Email</th><th>Status</th><th>Type</th><th>Actions</th></tr></thead><tbody>${rows.length?rows.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.email)}</td><td><span class="pill">${esc(c.status)}</span></td><td>${esc(c.type)}</td><td>${btn('View','view-customer:'+c.id)} ${btn('Edit','edit-customer:'+c.id)} ${btn('Delete','delete-customers:'+c.id,'danger')}</td></tr>`).join(''):emptyRow(5)}</tbody></table></div>`}
function customers(){const rows=filtered(state.customers,['name','email','company','status','type','source']);return `<div class="titleRow"><div><h1>Customers</h1><p>${rows.length} records · profiles, notes and related activity.</p></div><div class="actions">${btn('⇩ Import CSV','import-customers')} ${btn('⇧ Export CSV','export-customers')} ${btn('＋ Add customer','add-customer','primary')}</div></div><section class="pagePanel">${customerTable(rows)}</section>`}
function leads(){const rows=filtered(state.leads,['name','email','source','stage','priority']);return `<div class="titleRow"><div><h1>Leads</h1><p>Capture, qualify and convert opportunities.</p></div>${btn('＋ New lead','add-lead','primary')}</div><section class="pagePanel">${table(['Lead','Source','Stage','Value','Priority','Actions'],rows,x=>`<b>${esc(x.name)}</b>|${esc(x.source)}|<span class="pill">${esc(x.stage)}</span>|${money(x.value)}|${esc(x.priority)}|${btn('Edit','edit-lead:'+x.id)} ${btn('Delete','delete-leads:'+x.id,'danger')}`)}</section>`}
function deals(){const stages=['New','Qualified','Proposal','Negotiation','Won','Lost'];return `<div class="titleRow"><div><h1>Sales pipeline</h1><p>Track opportunities from qualification to close.</p></div>${btn('＋ New deal','add-deal','primary')}</div><div class="kanban">${stages.map(s=>`<section class="column"><div class="colHead"><b>${s}</b><span>${state.deals.filter(d=>d.stage===s).length}</span></div>${state.deals.filter(d=>d.stage===s).map(d=>`<article class="deal"><b>${esc(d.name)}</b><small>${esc(d.customer)}</small><strong>${money(d.value)}</strong><small>${Number(d.probability)||0}% probability</small><select data-deal-stage="${d.id}">${stages.map(o=>`<option ${o===d.stage?'selected':''}>${o}</option>`).join('')}</select><div class="actions">${btn('Edit','edit-deal:'+d.id)} ${btn('Delete','delete-deals:'+d.id,'danger')}</div></article>`).join('')||empty('No deals')}</section>`).join('')}</div>`}
function tasks(){return `<div class="titleRow"><div><h1>Tasks & Follow-ups</h1><p>Never miss the next action.</p></div>${btn('＋ New task','add-task','primary')}</div><section class="pagePanel">${table(['Task','Due','Priority','Status','Actions'],filtered(state.tasks,['title','due','priority','status']),x=>`<b>${esc(x.title)}</b>|${esc(x.due)}|${esc(x.priority)}|<span class="pill">${esc(x.status)}</span>|${btn(x.status==='Done'?'Reopen':'Complete','toggle-task:'+x.id)} ${btn('Edit','edit-task:'+x.id)} ${btn('Delete','delete-tasks:'+x.id,'danger')}`)}</section>`}
function appointments(){return `<div class="titleRow"><div><h1>Appointments</h1><p>Schedule customer meetings and follow-ups.</p></div>${btn('＋ Schedule','add-appointment','primary')}</div><section class="pagePanel">${table(['Title','Customer','Date','Time','Status','Actions'],filtered(state.appointments,['title','customer','date','time','status']),x=>`<b>${esc(x.title)}</b>|${esc(x.customer)}|${esc(x.date)}|${esc(x.time)}|<span class="pill">${esc(x.status)}</span>|${x.status!=='Completed'?btn('Complete','complete-appointment:'+x.id):''} ${btn('Edit','edit-appointment:'+x.id)} ${btn('Delete','delete-appointments:'+x.id,'danger')}`)}</section>`}
function activities(){return `<div class="titleRow"><div><h1>Activities</h1><p>Calls, meetings, emails and notes in one timeline.</p></div>${btn('＋ Log activity','add-activity','primary')}</div><section class="pagePanel">${table(['Type','Customer','Summary','Date','Actions'],filtered(state.activities,['type','customer','summary','date']),x=>`<span class="pill">${esc(x.type)}</span>|${esc(x.customer)}|${esc(x.summary)}|${esc(x.date)}|${btn('Edit','edit-activity:'+x.id)} ${btn('Delete','delete-activities:'+x.id,'danger')}`)}</section>`}
function reports(){const won=state.deals.filter(d=>d.stage==='Won'),revenue=won.reduce((a,d)=>a+Number(d.value||0),0),total=state.deals.length,closed=state.deals.filter(d=>['Won','Lost'].includes(d.stage)).length;const conversion=closed?Math.round(won.length/closed*100):0;return `<div class="titleRow"><div><h1>Reports</h1><p>Live calculations from your workspace data.</p></div>${btn('⇧ Export report','export-report')}</div><div class="cards">${card('Conversion rate',conversion+'%','Based on closed deals')} ${card('Won revenue',money(revenue),'Won deals')} ${card('Average deal',money(total?state.deals.reduce((a,d)=>a+Number(d.value||0),0)/total:0),'All deals')} ${card('Open tasks',state.tasks.filter(t=>t.status!=='Done').length,'Current')}</div><section class="panel"><div class="panelHead"><h3>Deal stage distribution</h3><span>${total} total deals</span></div>${['New','Qualified','Proposal','Negotiation','Won','Lost'].map(s=>{const n=state.deals.filter(d=>d.stage===s).length,p=total?Math.round(n/total*100):0;return `<div class="bar"><div><span>${s}</span><b>${n} · ${p}%</b></div><i><em style="width:${p}%"></em></i></div>`}).join('')}</section>`}
function documents(){return `<div class="titleRow"><div><h1>Documents</h1><p>Keep links to proposals, contracts and customer files.</p></div>${btn('＋ Add document','add-document','primary')}</div><section class="pagePanel">${table(['Document','Customer','Type','Date','Actions'],state.documents,x=>`<b>${esc(x.name)}</b>|${esc(x.customer)}|${esc(x.type)}|${esc(x.date)}|${x.url?btn('Open','open-url:'+encodeURIComponent(x.url)):''} ${btn('Edit','edit-document:'+x.id)} ${btn('Delete','delete-documents:'+x.id,'danger')}`)}</section>`}
function tags(){return `<div class="titleRow"><div><h1>Tags</h1><p>Organize customers with reusable labels.</p></div>${btn('＋ New tag','add-tag','primary')}</div><section class="pagePanel"><div class="tagGrid">${state.tags.map(t=>`<div class="tag"><span class="pill">${esc(t)}</span>${btn('Delete','delete-tag:'+encodeURIComponent(t),'danger')}</div>`).join('')||empty('No tags')}</div></section>`}
function team(){return `<div class="titleRow"><div><h1>Team & Roles</h1><p>Manage workspace members, roles and access status.</p></div>${btn('＋ Invite user','invite-user','primary')}</div><section class="pagePanel">${table(['Name','Email','Role','Status','Actions'],state.team,x=>`<b>${esc(x.name)}</b>|${esc(x.email)}|<span class="pill">${esc(x.role)}</span>|${esc(x.status)}|${btn('Edit role','edit-role:'+x.id)} ${btn('Delete','delete-team:'+x.id,'danger')}`)}</section>`}
function auditPage(){return `<div class="titleRow"><div><h1>Audit Log</h1><p>Track important workspace actions.</p></div>${btn('Clear log','clear-audit','danger')}</div><section class="pagePanel">${table(['Action','Entity','Date'],state.audit,x=>`${esc(x.action)}|${esc(x.entity)}|${esc(x.date)}`)}</section>`}
function settings(){return `<div class="titleRow"><div><h1>Settings</h1><p>White-label your deployment and control workspace preferences.</p></div>${btn('Save settings','save-settings','primary')}</div><section class="pagePanel formGrid"><label>App name<input id="set-name" value="${esc(state.name)}"></label><label>Currency<input id="set-currency" value="${esc(state.currency)}" maxlength="3"></label><label>Timezone<input id="set-timezone" value="${esc(state.timezone||'UTC')}"></label><label>Theme<select id="set-theme"><option ${state.theme==='Light'?'selected':''}>Light</option><option ${state.theme==='Dark'?'selected':''}>Dark</option></select></label><div class="wide"><h3>Data tools</h3>${btn('⇩ Backup JSON','backup')} ${btn('⇧ Restore JSON','restore')} ${btn('Reset demo data','reset-demo','danger')}</div></section>`}
function table(headers,rows,format){return `<div class="tableWrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(x=>`<tr>${format(x).split('|').map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):emptyRow(headers.length)}</tbody></table></div>`}
function empty(msg){return `<div class="empty">${esc(msg)}</div>`}function emptyRow(n){return `<tr><td colspan="${n}">${empty('No records found.')}</td></tr>`}
function modal(title,fields,submit,meta={}){document.querySelector('#modal')?.remove();const body=fields.map(f=>`<label>${esc(f.label)}${f.type==='textarea'?`<textarea id="f-${f.key}" ${f.required?'required':''} placeholder="${esc(f.placeholder||'')}">${esc(f.value||'')}</textarea>`:f.type==='select'?`<select id="f-${f.key}">${f.options.map(o=>`<option ${String(o)===String(f.value)?'selected':''}>${esc(o)}</option>`).join('')}</select>`:`<input id="f-${f.key}" type="${f.type||'text'}" value="${esc(f.value||'')}" ${f.required?'required':''} placeholder="${esc(f.placeholder||'')}">`}</label>`).join('');document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><form class="modalBox" id="modalForm" data-mode="${esc(meta.mode||'create')}" data-arr="${esc(meta.arr||'')}" data-id="${esc(meta.id||'')}"><div class="panelHead"><h2>${esc(title)}</h2><button type="button" class="icon" data-action="close-modal">×</button></div><div class="formGrid">${body}</div><div class="modalActions"><button type="button" class="secondary" data-action="close-modal">Cancel</button><button class="primary">${esc(submit||'Save')}</button></div></form></div>`);document.querySelector('#modalForm').onsubmit=formSubmit;document.querySelector('#modal')?.querySelector('input,select,textarea')?.focus()}
function f(key,label,required=0,type='text',options=[],value=''){return {key,label,required,type,options,value}}
function customerFields(c={}){return [f('name','Name',1,'text',[],c.name),f('email','Email',1,'email',[],c.email),f('phone','Phone',0,'text',[],c.phone),f('company','Company',0,'text',[],c.company),f('status','Status',0,'select',['Active','At Risk','Inactive'],c.status||'Active'),f('type','Type',0,'select',['SMB','Enterprise','Agency','Services','Education','Other'],c.type||'SMB'),f('source','Source',0,'text',[],c.source||'Manual'),f('notes','Notes',0,'textarea',[],c.notes)]}
function bindView(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;search='';render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));document.querySelectorAll('[data-deal-stage]').forEach(s=>s.onchange=()=>update('deals',Number(s.dataset.dealStage),{stage:s.value},'deal'));const modalEl=document.querySelector('#modal');if(modalEl)modalEl.onclick=e=>{if(e.target===modalEl)modalEl.remove()}}
function action(a){if(a==='collapse'){document.querySelector('#side')?.classList.toggle('collapsed');return}if(a==='notify'){return notificationPanel()}if(a==='signout'){if(confirm('Sign out of this demo workspace?')){state.session=false;save();render()}return}if(a==='signin'){state.session=true;save();render();return}if(a.startsWith('goto-')){const target=a.slice(5);const map={customers:'Customers',leads:'Leads',deals:'Deals',tasks:'Tasks'};if(!map[target])return toast('Destination not available','error');page=map[target];search='';render();return}if(a==='close-modal'){document.querySelector('#modal')?.remove();return}
if(a.startsWith('delete-')){const [x,idRaw]=a.split(':');const arr=x.replace('delete-','');if(x==='delete-tag'){const tag=decodeURIComponent(idRaw);if(confirm('Delete this tag?')){state.tags=state.tags.filter(t=>t!==tag);state.customers.forEach(c=>c.tags=(c.tags||[]).filter(t=>t!==tag));audit('Deleted tag',tag);save();toast('Tag deleted');render()}return}if(x==='delete-team'&&state.team.length<=1)return toast('Keep at least one team member','error');const singular={customers:'customer',leads:'lead',deals:'deal',tasks:'task',appointments:'appointment',activities:'activity',documents:'document',team:'team member'};del(arr,Number(idRaw),singular[arr]||arr.slice(0,-1));return}
if(a.startsWith('toggle-task:')){const id=Number(a.split(':')[1]),t=state.tasks.find(t=>t.id===id);if(t)update('tasks',id,{status:t.status==='Done'?'Open':'Done'},'task');return}
if(a.startsWith('complete-appointment:')){update('appointments',Number(a.split(':')[1]),{status:'Completed'},'appointment');return}
if(a.startsWith('view-customer:'))return customerDetail(Number(a.split(':')[1]));
if(a.startsWith('edit-customer:')){const id=Number(a.split(':')[1]),c=state.customers.find(x=>x.id===id);if(c)modal('Edit customer',customerFields(c),'Save changes',{mode:'edit',arr:'customers',id});return}
if(a==='add-customer')return modal('Add customer',customerFields(), 'Create customer');
if(a.startsWith('edit-lead:')){const x=state.leads.find(x=>x.id===Number(a.split(':')[1]));if(x)modal('Edit lead',[f('name','Name',1,'text',[],x.name),f('email','Email',1,'email',[],x.email),f('source','Source',0,'text',[],x.source),f('value','Value',1,'number',[],x.value),f('stage','Stage',0,'select',['New','Qualified','Proposal','Negotiation','Won','Lost'],x.stage),f('priority','Priority',0,'select',['High','Medium','Low'],x.priority)],'Save changes',{mode:'edit',arr:'leads',id:x.id});return}
if(a==='add-lead')return modal('New lead',[f('name','Name',1),f('email','Email',1,'email'),f('source','Source'),f('value','Value',1,'number'),f('stage','Stage',0,'select',['New','Qualified','Proposal','Negotiation','Won','Lost'],'New'),f('priority','Priority',0,'select',['High','Medium','Low'],'Medium')],'Create lead');
if(a.startsWith('edit-deal:')){const x=state.deals.find(x=>x.id===Number(a.split(':')[1]));if(x)modal('Edit deal',[f('name','Deal name',1,'text',[],x.name),f('customer','Customer',1,'text',[],x.customer),f('value','Value',1,'number',[],x.value),f('probability','Probability %',1,'number',[],x.probability),f('stage','Stage',0,'select',['New','Qualified','Proposal','Negotiation','Won','Lost'],x.stage)],'Save changes',{mode:'edit',arr:'deals',id:x.id});return}
if(a==='add-deal')return modal('New deal',[f('name','Deal name',1),f('customer','Customer',1),f('value','Value',1,'number'),f('probability','Probability %',1,'number',[],50),f('stage','Stage',0,'select',['New','Qualified','Proposal','Negotiation','Won','Lost'],'New')],'Create deal');
if(a.startsWith('edit-task:')){const x=state.tasks.find(x=>x.id===Number(a.split(':')[1]));if(x)modal('Edit task',[f('title','Task',1,'text',[],x.title),f('due','Due date',1,'text',[],x.due),f('priority','Priority',0,'select',['High','Medium','Low'],x.priority),f('status','Status',0,'select',['Open','Done'],x.status)],'Save changes',{mode:'edit',arr:'tasks',id:x.id});return}
if(a==='add-task')return modal('New task',[f('title','Task',1),f('due','Due date',1),f('priority','Priority',0,'select',['High','Medium','Low'],'Medium')],'Create task');
if(a.startsWith('edit-appointment:')){const x=state.appointments.find(x=>x.id===Number(a.split(':')[1]));if(x)modal('Edit appointment',[f('title','Title',1,'text',[],x.title),f('customer','Customer',1,'text',[],x.customer),f('date','Date',1,'date',[],x.date),f('time','Time',1,'time',[],x.time),f('status','Status',0,'select',['Scheduled','Completed','Cancelled'],x.status)],'Save changes',{mode:'edit',arr:'appointments',id:x.id});return}
if(a==='add-appointment')return modal('Schedule appointment',[f('title','Title',1),f('customer','Customer',1),f('date','Date',1,'date'),f('time','Time',1,'time')],'Schedule');
if(a.startsWith('edit-activity:')){const x=state.activities.find(x=>x.id===Number(a.split(':')[1]));if(x)modal('Edit activity',[f('type','Type',0,'select',['Call','Email','Meeting','Note','Follow-up','Other'],x.type),f('customer','Customer',1,'text',[],x.customer),f('summary','Summary',1,'textarea',[],x.summary)],'Save changes',{mode:'edit',arr:'activities',id:x.id});return}\nif(a==='add-activity')return modal('Log activity',[f('type','Type',0,'select',['Call','Email','Meeting','Note','Follow-up','Other'],'Note'),f('customer','Customer',1),f('summary','Summary',1,'textarea')],'Log activity');
if(a.startsWith('edit-document:')){const x=state.documents.find(x=>x.id===Number(a.split(':')[1]));if(x)modal('Edit document',[f('name','Document name',1,'text',[],x.name),f('customer','Customer',1,'text',[],x.customer),f('type','Type',0,'text',[],x.type),f('url','Document URL',0,'url',[],x.url)],'Save changes',{mode:'edit',arr:'documents',id:x.id});return}
if(a==='add-document')return modal('Add document',[f('name','Document name',1),f('customer','Customer',1),f('type','Type'),f('url','Document URL',0,'url')],'Add document');
if(a.startsWith('open-url:')){const url=decodeURIComponent(a.slice(9));try{const u=new URL(url);if(['http:','https:'].includes(u.protocol))window.open(u.href,'_blank','noopener,noreferrer');else toast('Only HTTP(S) links can be opened','error')}catch{toast('Invalid URL','error')}return}
if(a==='add-tag')return modal('New tag',[f('tag','Tag name',1)],'Create tag');
if(a.startsWith('edit-role:')){const x=state.team.find(x=>x.id===Number(a.split(':')[1]));if(x)modal('Edit team role',[f('name','Name',1,'text',[],x.name),f('email','Email',1,'email',[],x.email),f('role','Role',0,'select',['Owner','Admin','Manager','Sales','Staff'],x.role),f('status','Status',0,'select',['Active','Invited','Suspended'],x.status)],'Save changes',{mode:'edit',arr:'team',id:x.id});return}
if(a==='invite-user')return modal('Invite team member',[f('name','Name',1),f('email','Email',1,'email'),f('role','Role',0,'select',['Admin','Manager','Sales','Staff'],'Staff')],'Create invitation');
if(a==='clear-notifications'){state.notifications=[];save();toast('Notifications marked as read');document.querySelector('#modal')?.remove();render();return}
if(a==='clear-audit'){if(!state.audit.length)return toast('Audit log is already empty');if(confirm('Clear the entire audit log?')){state.audit=[];save();toast('Audit log cleared');render()}return}
if(a==='save-settings'){const name=document.querySelector('#set-name')?.value.trim()||'WyDoc CRM',currency=(document.querySelector('#set-currency')?.value.trim()||'USD').toUpperCase(),tz=document.querySelector('#set-timezone')?.value.trim()||'UTC',theme=document.querySelector('#set-theme')?.value==='Dark'?'Dark':'Light';if(!/^[A-Z]{3}$/.test(currency))return toast('Currency must be a 3-letter ISO code','error');state.name=name;state.currency=currency;state.timezone=tz;state.theme=theme;audit('Updated settings');save();toast('Settings saved');render();return}
if(a==='backup')return download('wydoc-crm-backup.json',JSON.stringify({...state,session:true},null,2),'application/json');
if(a==='restore'){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=()=>{const file=i.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const incoming=JSON.parse(r.result);if(!incoming||typeof incoming!=='object'||!Array.isArray(incoming.customers)||!Array.isArray(incoming.leads)||!Array.isArray(incoming.deals))throw new Error();state=normalize({...clone(baseDefaults),...incoming,session:true});audit('Restored backup');save();toast('Backup restored');render()}catch{toast('Invalid or incompatible backup file','error')}};r.readAsText(file)};i.click();return}
if(a==='reset-demo'){if(confirm('Reset all local data to demo data?')){state=clone(baseDefaults);save();toast('Demo data restored');render()}return}
if(a.startsWith('export-'))return exportCsv(a.slice(7));if(a==='import-customers'){const i=document.createElement('input');i.type='file';i.accept='.csv,text/csv';i.onchange=()=>importCsv(i.files?.[0]);i.click();return}
}
function formSubmit(e){e.preventDefault();const form=e.currentTarget,ids=[...form.querySelectorAll('[id^="f-"]')],d=Object.fromEntries(ids.map(i=>[i.id.slice(2),i.value.trim()]));if(!form.checkValidity()){form.reportValidity();return}const mode=form.dataset.mode,arr=form.dataset.arr,id=Number(form.dataset.id);if(mode==='edit'){if(arr==='customers'&&state.customers.some(c=>c.id!==id&&(c.email||'').toLowerCase()===(d.email||'').toLowerCase()))return toast('Another customer already uses that email','error');document.querySelector('#modal')?.remove();if(['leads','deals'].includes(arr)){ d.value=Number(d.value)||0;if(arr==='deals')d.probability=Math.max(0,Math.min(100,Number(d.probability)||0))}update(arr,id,d,arr.slice(0,-1));return}if(form.querySelector('h2').textContent==='Add customer'){if(state.customers.some(c=>(c.email||'').toLowerCase()===(d.email||'').toLowerCase())){document.querySelector('#modal')?.remove();return toast('A customer with that email already exists','error')}return add('customers',{...d,status:d.status||'Active',tags:[]},'customer');}if(form.querySelector('h2').textContent==='New lead')return add('leads',{...d,value:Number(d.value)||0},'lead');if(form.querySelector('h2').textContent==='New deal')return add('deals',{...d,value:Number(d.value)||0,probability:Math.max(0,Math.min(100,Number(d.probability)||0))},'deal');if(form.querySelector('h2').textContent==='New task')return add('tasks',{...d,status:'Open'},'task');if(form.querySelector('h2').textContent==='Schedule appointment')return add('appointments',{...d,status:'Scheduled'},'appointment');if(form.querySelector('h2').textContent==='Log activity')return add('activities',{...d,date:new Date().toLocaleString()},'activity');if(form.querySelector('h2').textContent==='Add document')return add('documents',{...d,date:new Date().toLocaleDateString()},'document');if(form.querySelector('h2').textContent==='New tag'){const tag=d.tag.replace(/\s+/g,' ').trim();if(!tag)return toast('Tag name is required','error');if(state.tags.some(t=>t.toLowerCase()===tag.toLowerCase()))return toast('That tag already exists','error');state.tags.push(tag);audit('Created tag',tag);save();document.querySelector('#modal')?.remove();toast('Tag created');return render()}if(form.querySelector('h2').textContent==='Invite team member')return add('team',{...d,status:'Invited'},'team member')}
function customerDetail(id){const c=state.customers.find(x=>x.id===id);if(!c)return toast('Customer not found','error');const deals=state.deals.filter(d=>d.customer===c.name),acts=state.activities.filter(a=>a.customer===c.name),apps=state.appointments.filter(a=>a.customer===c.name);document.querySelector('#modal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="modalBox"><div class="panelHead"><div><h2>${esc(c.name)}</h2><p>${esc(c.email)} · ${esc(c.phone||'')}</p></div><button class="icon" data-action="close-modal">×</button></div><div class="profileGrid"><div><b>Company</b><span>${esc(c.company||'—')}</span></div><div><b>Status</b><span>${esc(c.status)}</span></div><div><b>Type</b><span>${esc(c.type||'—')}</span></div><div><b>Source</b><span>${esc(c.source||'—')}</span></div></div><section class="profileSection"><h3>Notes</h3><p>${esc(c.notes||'No notes yet.')}</p></section><section class="profileSection"><h3>Deals (${deals.length})</h3>${deals.length?deals.map(d=>`<div class="miniRow"><span>${esc(d.name)}</span><b>${money(d.value)}</b><span class="pill">${esc(d.stage)}</span></div>`).join(''):empty('No related deals')}</section><section class="profileSection"><h3>Activity (${acts.length})</h3>${acts.length?acts.slice(0,8).map(x=>`<div class="miniRow"><span>${esc(x.type)} · ${esc(x.summary)}</span><small>${esc(x.date)}</small></div>`).join(''):empty('No activities')}</section><section class="profileSection"><h3>Appointments (${apps.length})</h3>${apps.length?apps.map(x=>`<div class="miniRow"><span>${esc(x.title)}</span><small>${esc(x.date)} ${esc(x.time)}</small></div>`).join(''):empty('No appointments')}</section><div class="modalActions">${btn('Edit customer','edit-customer:'+c.id,'primary')}<button type="button" class="secondary" data-action="close-modal">Close</button></div></div></div>`);bindView()}
function notificationPanel(){document.querySelector('#modal')?.remove();const notes=state.notifications.length?state.notifications.map(n=>`<div class="miniRow"><span>${esc(n.message)}</span><small>${esc(n.date)}</small></div>`).join(''):empty('No new notifications');document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="modalBox smallBox"><div class="panelHead"><h2>Notifications</h2><button class="icon" data-action="close-modal">×</button></div>${notes}<div class="modalActions">${state.notifications.length?btn('Mark all read','clear-notifications','primary'):''}<button class="secondary" data-action="close-modal">Close</button></div></div></div>`);bindView()}
function exportCsv(kind){const map={customers:state.customers,leads:state.leads,deals:state.deals,tasks:state.tasks,report:[{metric:'Customers',value:state.customers.length},{metric:'Leads',value:state.leads.length},{metric:'Deals',value:state.deals.length},{metric:'Won revenue',value:state.deals.filter(d=>d.stage==='Won').reduce((a,d)=>a+Number(d.value||0),0)},{metric:'Open tasks',value:state.tasks.filter(t=>t.status!=='Done').length}]};const rows=map[kind]||[];if(!rows.length)return toast('Nothing to export','error');const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];const csv=[keys.map(csvCell).join(','),...rows.map(r=>keys.map(k=>csvCell(r[k])).join(','))].join('\r\n');download(`wydoc-${kind}.csv`,csv,'text/csv;charset=utf-8');toast('Export ready')}
function csvCell(v){return `"${String(Array.isArray(v)?v.join('; '):v??'').replace(/"/g,'""')}"`}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(quoted){if(ch==='"'&&next==='"'){cell+='"';i++}else if(ch==='"')quoted=false;else cell+=ch}else if(ch==='"')quoted=true;else if(ch===','){row.push(cell);cell=''}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=ch}if(cell.length||row.length){row.push(cell.replace(/\r$/,''));rows.push(row)}return rows.filter(r=>r.some(x=>x.trim()!==''))}
function importCsv(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const rows=parseCsv(r.result);if(rows.length<2)throw new Error();const headers=rows.shift().map(h=>h.trim().toLowerCase());const nameIndex=headers.indexOf('name')>=0?headers.indexOf('name'):headers.indexOf('customer');if(nameIndex<0)throw new Error();let added=0,skipped=0;for(const cols of rows){const name=(cols[nameIndex]||'').trim();if(!name){skipped++;continue}const email=(cols[headers.indexOf('email')]||'').trim();if(state.customers.some(c=>c.email&&email&&c.email.toLowerCase()===email.toLowerCase())){skipped++;continue}state.customers.unshift({id:nextId(),name,email,phone:(cols[headers.indexOf('phone')]||'').trim(),company:(cols[headers.indexOf('company')]||name).trim(),status:(cols[headers.indexOf('status')]||'Active').trim(),type:(cols[headers.indexOf('type')]||'Other').trim(),source:(cols[headers.indexOf('source')]||'CSV').trim(),tags:[],notes:(cols[headers.indexOf('notes')]||'').trim()});added++}audit('Imported customers',`${added} records${skipped?`, ${skipped} skipped`:''}`);save();toast(`${added} customers imported`);render()}catch{toast('CSV could not be imported. Include a Name/Customer column.','error')}};r.readAsText(file)}
function download(name,data,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
if(!state.notifications.length&&state.tasks.some(t=>t.status!=='Done')){state.notifications=[{id:nextId(),message:'You have open tasks that need attention.',date:new Date().toLocaleString()}];save()}
render();
